on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: javascript-action-runner
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: kblogin123456/hello-world-javascript-action@v1.16
        with:
          application: 'MYAPP'
          applicationProcess: 'DEPLOY-HFS'
          environment: 'DEV'
          versions: 'hfs_only_rabo_uid'
          component: 'MYCOMP'
          hostname: '${{ secrets.UCD_HOST }}'
          username: '${{ secrets.UCD_USERNAME }}'
          password: '${{ secrets.UCD_PASSWORD }}'
