on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: self-hosted
    environment: DEV
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: bharathk-github/UrbanCodeDeployAction@v1.29
        with:
          application: 'MYAPP'
          applicationProcess: 'DEPLOY-MYAPP'
          environment: 'DEV'
          properties: '{"prop1":"${{ vars.PROP1 }}", "prop2":"${{ vars.PROP2 }}"}'
          propertiesfile: 'ucdproperties'
          versions: '[{"version": "BUILD-DEV-JCL", "component": "MYCOMP"}]'
          hostname: '${{ secrets.UCD_HOST }}'
          port: '8443'
          username: '${{ secrets.UCD_USERNAME }}'
          password: '${{ secrets.UCD_PASSWORD }}'
          authToken: '${{ secrets.UCD_AUTHTOKEN }}'
          disableSSLVerification: 'true'
